# Default values for app-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  name: ""
  tag: ""
serviceAccount:
  create: true
  name: "default-service-account" 