apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: appimage
    context: ./
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: app-development
      chartPath: app-helm
      namespace: "app01"
      createNamespace: true
      setValueTemplates:
        image.name: "appimage"
        image.tag: "{{.IMAGE_TAG_appimage}}"
        serviceAccountName.name: "app01-service-account"
 
