apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: simpleapp=ctmnz/simpleapp:latest
    argocd-image-updater.argoproj.io/simpleapp.update-strategy: digest
  name: app01live
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app01live
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: app-helm
    repoURL: docker.io/ctmnz
    targetRevision: 0.1.2
    helm:
      parameters:
        - name: "image.name"
          value: ctmnz/simpleapp
        - name: "image.tag"
          value: latest 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
