apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: simpleapp=docker.io/ctmnz/simpleapp:latest
    argocd-image-updater.argoproj.io/simpleapp.update-strategy: latest
    argocd-image-updater.argoproj.io/simpleapp.allow-tags: latest
  name: app01live
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app01live
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ctmnz/skaffold-development/
    targetRevision: livedemo
    path: Skaffold/k8s/livedemo/ 
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
