apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: simpleapp=docker.io/ctmnz/simpleapp:latest
    argocd-image-updater.argoproj.io/simpleapp.update-strategy: latest
    argocd-image-updater.argoproj.io/simpleapp.allow-tags: latest
  name: app01live
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app01live
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: app-helm
    repoURL: docker.io/ctmnz
    targetRevision: 0.1.0
    helm:
      releaseName: app01live
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
